### ISSUE TITLE
Use with django-registration?

### ISSUE THREAD

**Issue by the-mace** [Zeioth/django-dual-authentication#4]
Hi i'm using django-registration (https://django-registration.readthedocs.io/en/2.1.1/) and it seems when using that this dual authentication doesnt work (just get the standard failure to login with email and password). Any ideas how to get around that and have both work?

settings file config items:
# Auth with username or email
AUTHENTICATION_BACKENDS = ['django-dual-authentication.backends.DualAuthentication']
AUTHENTICATION_CASE_SENSITIVE = "username"

Note that django-registration requires:
                  # Registration
                  url(r'^accounts/', include('registration.backends.hmac.urls')),

Thanks

**Comment by Zeioth** [comment]
Hello the-mace. This is probably caused because  django-registration also overrides the authentication backend. You have several options here:

* Personally, I would recommend you a registration system like [Djoser](https://github.com/sunscrapers/djoser) since it's much easier to extend and scale. Also, you can use it with any authentication backend (like us).
* If possible, Import django-registration before django-dual-authentication. Since we only override the login system, registration should keep working.
* django-dual-authentication code it's extremely simple. You can override django-registration and copy-paste our backend.

In my experience, the first option is the best one. Good luck.

**Comment by the-mace** [comment]
Thank you for the quick and thorough response with multiple options. Never heard of Djoser so will check that out. My site is already up and running so i'll have to be careful on a transition.

Many thanks for your contribution and help.

**Comment by the-mace** [comment]
In case anyone else does the same dumb thing I did, django-dual-authentication works just fine with django-registration. The issue was on my test setup I had multiple users with the same email address so it looked like email auth didnt work. Once I cleaned that up both work together fine.

**Comment by Zeioth** [comment]
Thank you for the feedback!
